version: "3.9"

services:
  api:
    build: .
    container_name: qualite_air_api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models   # Monte le dossier models en local
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
